# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 766f1e6f10c70aaa9af7915c7b0578871294199f5b78d53909a40bd3198a8d908a10627f3800bc14cd1490483c13c1d78895c3866e972d5f8976646589a552c2

test:
  secret_key_base: a52e8cff6ae1c9c16bc228030c3c752476244df2607db4adbf30808e0c3093909e95a461b978872a2f9df643f9d48cf606bef386ae7893a4ea2b3c96bc35169e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
